# Generated by Django 3.2.18 on 2024-04-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0026_client_multiple_response_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsakey',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
